services:
  postgres:
    image: postgres
    volumes:
      - postgresdb:/var/lib/postgresql/data
    container_name: postgres
    user: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready', '-h', 'localhost', '-U', 'postgres' ]
  news_api:
    image: news_api
    command: python news_api/manage.py runserver 0.0.0.0:8000
    container_name: news_api
    build:
      context: ./news_api/
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      API_KEY: eea7535495b44f79b86decfc6eff5bb3
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgresdb: