# Generated by Django 4.1.3 on 2022-11-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.CharField(blank=True, max_length=250, verbose_name='Image url'),
        ),
        migrations.AlterField(
            model_name='news',
            name='source_url',
            field=models.CharField(max_length=250, verbose_name='Source url'),
        ),
    ]
