# Generated by Django 4.1.3 on 2022-11-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_image_url_alter_news_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.CharField(blank=True, max_length=400, verbose_name='Image url'),
        ),
        migrations.AlterField(
            model_name='news',
            name='source_url',
            field=models.CharField(max_length=400, verbose_name='Source url'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=400, verbose_name='Title'),
        ),
    ]
