# Generated by Django 4.1.3 on 2023-02-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_country_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Image url'),
        ),
        migrations.AlterField(
            model_name='news',
            name='source_url',
            field=models.CharField(max_length=1000, verbose_name='Source url'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Title'),
        ),
    ]
